Add Connection and FortiCare Info
AsBuiltReport/AsBuiltReport.Fortinet.Fortigate pull request #1
Opened 2022-05-18 19:18 UTC by alagoutte

Add Initial Connection (and Disconnect) using PowerFGT

Display FortiCare info (Status, support, Firmware...)

2022-05-24 23:34 UTC, tpcarman requested changes
Updates/changes required as per comments.

2022-05-24 23:34 UTC, tpcarman commented on Src/Public/Invoke-AsBuiltReport.Fortinet.Fortigate.ps1
> +        Connect-FGT -Server $System -Credential $Credential -SkipCertificateCheck | Out-Null #-Port $Options.ServerPort
I would suggest adding more error handling by using Try / Catch

2022-05-24 23:34 UTC, tpcarman commented on Src/Public/Invoke-AsBuiltReport.Fortinet.Fortigate.ps1
> +        Section -Style Heading1 'Implementation Report' {
Use the system name as the top level heading, this works better when running against multiple systems

2022-05-24 23:34 UTC, tpcarman commented on Src/Private/Get-AbrFgtForticare.ps1
> +        Section -Style Heading2 'FortiCare' {
you need to add an If statement. Section headings should only be shown if the information to report on is available.

2022-05-24 23:34 UTC, tpcarman commented on Src/Private/Get-AbrFgtForticare.ps1
> +                List = $true
All tables must have set column widths. Table names should include the system name or object which they relate to. Please also include the `ShowTableCaptions` option for all tables.

```
$TableParams = @{
    Name = "Forticare - $($System)"
    List = $true
    ColumnWidths = 50, 50
}
if ($Report.ShowTableCaptions) {
    $TableParams['Caption'] = "- $($TableParams.Name)"
}
$OutObj | Table @TableParams
```

2022-05-25 10:48 UTC, tpcarman requested changes
All tables require set columnwidths to improve document readability and formatting. Try and keep column widths consistent where possible. This might take a few attempts to get it looking clean. Try to avoid word wrap of table headings wherever possible by adjusting the columnwidth or using `Headers` within the TableParams to provide a shortname for the heading.

Example:
```
$TableParams = @{
                        Name = "Disk Specifications - $($VxrHost.hostname)"
                        Headers = 'Encl', 'Slot', 'Serial Number', 'Type', 'Capacity', 'Speed', 'Status', 'Firmware'
                        Columns = 'Enclosure', 'Slot', 'Serial Number', 'Disk Type', 'Capacity', 'Speed', 'Status', 'Firmware'
                        ColumnWidths = 9, 9, 22, 10, 14, 12, 12, 12
                    }
```

2022-05-25 10:48 UTC, tpcarman commented on Src/Private/Get-AbrFgtForticare.ps1
> +                    List = $true
Add `ColumnWidths = 50, 50`

2022-05-25 10:48 UTC, tpcarman commented on Src/Private/Get-AbrFgtForticare.ps1
> +                    List = $false
Add `ColumnWidths = 25, 25, 25, 25`

2022-05-25 10:48 UTC, tpcarman commented on Src/Private/Get-AbrFgtForticare.ps1
> +                    List = $true
Add `ColumnWidths = 50, 50`

2022-05-25 12:41 UTC, alagoutte commented
> All tables require set columnwidths to improve document readability and formatting. Try and keep column widths consistent where possible. This might take a few attempts to get it looking clean. Try to avoid word wrap of table headings wherever possible by adjusting the columnwidth or using `Headers` within the TableParams to provide a shortname for the heading.
> 
> Example:
> 
> ```
> $TableParams = @{
>                         Name = "Disk Specifications - $($VxrHost.hostname)"
>                         Headers = 'Encl', 'Slot', 'Serial Number', 'Type', 'Capacity', 'Speed', 'Status', 'Firmware'
>                         Columns = 'Enclosure', 'Slot', 'Serial Number', 'Disk Type', 'Capacity', 'Speed', 'Status', 'Firmware'
>                         ColumnWidths = 9, 9, 22, 10, 14, 12, 12, 12
>                     }
> ```

Oups... forget this part on the change, i will update my patch

2022-06-07 00:38 UTC, tpcarman approved these changes

2022-06-07 00:40 UTC, merged